config/routes.rb
DSS::Application.routes.draw do

  mount Mapas::Engine, at: "/eM"
  

  mount Escenarios::Engine, at: "/eEE"
  

  

  root :to => 'inicio#inicio'
  get "governance/get_functions"
  post "governance/get_structure"
  post "governance/update_structure"
  post "governance/get_responsabilities"
  get "governance/structures"
  post "governance/add_structure"
  post "governance/add_responsability"
  get "autocomplete/responsabilities"

  get "enterprises/new"
  get "enterprises/get_enterprise"
  get "enterprises/edit"
  post "enterprises/update"
  post "enterprises/resultado"
  post "config/resultado"
  get "config/riskmap" # Change to GET, provided the session use
  
  get "inicio/inicio"
  get '/admin', to: 'inicio#admin', :as => 'administrar'

  post "inicio/getFilterEmpresa" # Information to select what-to-generate
  post "inicio/g_home" # Initial screen
  post "inicio/g_decision_maps" # Decision Maps
  post "inicio/g_goal_escenarios" # Goal Assessment Scenarios 
  post "inicio/g_risk_escenarios" # Risk Assessment Scenarios
  post "inicio/g_priorization_escenarios" # Prioritization Scenarios
  post "inicio/session_config" # Session Configuration
end

app/views/layouts/application.en.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InvestIT</title>

  <link rel="stylesheet" href="/assets/my_jquery.css" />
  <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script> 
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <script>
    // SLA: Modification of the JQUERY autocomplete, to underline the caracters matching the search
  String.prototype.replaceAt = function(index, char) 
  {
    return this.substr(0, index) + "<span style='font-weight:bold;color:#FF8E2B;'>" + char + "</span>";
  }

  $.ui.autocomplete.prototype._renderItem = function(ul, item) {
    this.term = this.term.toLowerCase().trim();

    var resultStr = item.label.toString().toLowerCase().trim();
    var t = "";
    while (resultStr.indexOf(this.term) != -1) {
        var index = resultStr.indexOf(this.term);
        t = t + item.label.toString().trim().replaceAt(index, item.label.toString().trim().slice(index, index + this.term.length));
        resultStr = resultStr.substr(index + this.term.length);
        item.label = item.label.toString().trim().substr(index + this.term.length);
    }
    return $("<li></li>").data("item.autocomplete", item).append("<a>" + t + item.label + "</a>").appendTo(ul);

  };
  // SLA: Modification of the JQUERY autocomplete, to underline the caracters matching the search

  </script>

</head>
<body>

<% if !alert.nil? && !alert.empty? %>
<div class="alert alert-danger" style="padding:10px;">
    <%= alert %>
</div>
<% end %>

<% if !notice.nil? && !notice.empty? %>
<div class="alert alert-info" style="padding:10px;">
    <%= notice %>
</div>
<% end %>

<div>
  <p style="text-align:right;">
    <% emp = getMyEnterprise %>
    <img src="../assets/online.png">
    <%= 'Default User' %> |
    <img src="../assets/enterprise.png">
    <% if !emp.nil? %>
    Enterprise: <span id="myEnterprise" style="text-transform:uppercase;"><%= emp.name %></span> |
    <% else %>
    Enterprise: <span id="myEnterprise" style="text-transform:uppercase;"> - </span> |
    <% end %> 
    <img src="../assets/key.png">
    <%= link_to "Administration", administrar_path %> | 

    <img src="../assets/home.png">
    <%= link_to "Home", root_path %>
  </p>
</div>


<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InvestIT</title>

  <link rel="stylesheet" href="/assets/my_jquery.css" />
  <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script> 
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <script>
    // SLA: Modificacion del autocomplete de JQUERY, para marcar los caracteres que concuerdan con la busqueda
  String.prototype.replaceAt = function(index, char) 
  {
    return this.substr(0, index) + "<span style='font-weight:bold;color:#FF8E2B;'>" + char + "</span>";
  }

  $.ui.autocomplete.prototype._renderItem = function(ul, item) {
    this.term = this.term.toLowerCase().trim();

    var resultStr = item.label.toString().toLowerCase().trim();
    var t = "";
    while (resultStr.indexOf(this.term) != -1) {
        var index = resultStr.indexOf(this.term);
        t = t + item.label.toString().trim().replaceAt(index, item.label.toString().trim().slice(index, index + this.term.length));
        resultStr = resultStr.substr(index + this.term.length);
        item.label = item.label.toString().trim().substr(index + this.term.length);
    }
    return $("<li></li>").data("item.autocomplete", item).append("<a>" + t + item.label + "</a>").appendTo(ul);

  };
  // SLA: Modificacion del autocomplete de JQUERY, para marcar los caracteres que concuerdan con la busqueda

  </script>

</head>
<body>

<% if !alert.nil? && !alert.empty? %>
<div class="alert alert-danger" style="padding:10px;">
    <%= alert %>
</div>
<% end %>

<% if !notice.nil? && !notice.empty? %>
<div class="alert alert-info" style="padding:10px;">
    <%= notice %>
</div>
<% end %>

<div>
  <p style="text-align:right;">
    <% emp = getMyEnterprise %>
    <img src="../assets/online.png">
    <%= 'Usuario' %> |
    <img src="../assets/enterprise.png">
    <% if !emp.nil? %>
    Empresa: <span id="myEnterprise" style="text-transform:uppercase;"><%= emp.name %></span> |
    <% else %>
    Empresa: <span id="myEnterprise" style="text-transform:uppercase;"> - </span> |
    <% end %> 
    <img src="../assets/key.png">
    <%= link_to "Administración", administrar_path %> | 

    <img src="../assets/home.png">
    <%= link_to "Inicio", root_path %>
  </p>
</div>


<%= yield %>

</body>
</html>